### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by BumiMandiasDev** [azgaresncf/bananasquad#2]
Thanks lmfao no clue where this appeared from, typically I stay pretty safe. But oddly enough I found a hvnc.py on my computer and some of my info saved.

**Comment by BumiMandiasDev** [comment]
It appears FunCaptcha.ru is inaccessible so I cannot dig into the actual malware atm but appreciate the post

**Comment by vural2123** [comment]
It worked for me, thank you. I found more info than what you mentioned, but I'm not sure. If you have more information on this subject, could you please share it?

**Comment by azgaresncf** [comment]
> Thanks lmfao no clue where this appeared from, typically I stay pretty safe. But oddly enough I found a hvnc.py on my computer and some of my info saved.

Don't worry, it's totally normal!

On most of the articles I've seen mentioning the virus in question, it's mainly Python packages usurping the name of other packages, and containing the virus in question.

**Comment by azgaresncf** [comment]
> It appears FunCaptcha.ru is inaccessible so I cannot dig into the actual malware atm but appreciate the post

In itself, it's a good thing that the virus is becoming less and less accessible. The only problem is that we can't investigate further how the virus works.

**Comment by vural2123** [comment]
> > It appears FunCaptcha.ru is inaccessible so I cannot dig into the actual malware atm but appreciate the post
> 
> In itself, it's a good thing that the virus is becoming less and less accessible. The only problem is that we can't investigate further how the virus works.

I think it's because of a source on gitbuh, I just checked the virus on github and noticed they deleted it.
